@startuml ficheros
class Usuario {
    - Codigo:String
    - aficiones: List<String>
}

class Fichero {
    - usuarios: List<Usuario>
    - ficheros: List<Fichero>

    + leerFichero()
    + mostrarFicheros()
    + generarCodigo()
    + anyadirUsuario()
    + mostrarUsuarios()
    + compararPareja()
    + generarFicheroConcordancia()
}

Usuario <..> Fichero : usa
@enduml