@startuml ficheros
class Usuario {
    - codigo: String
    - aficiones: List<String>
    + toString()
    + toFormatoFichero()
}

class Pareja {
    - usuario1: Usuario
    - usuario2: Usuario
    - numeroConcordancia: int
    + toString()
}

class Fichero {
    - nombreFichero: String
    - usuarios: List<Usuario>
    - ficheros: List<Fichero>

    + leerFichero()
    + cargarFicheros()
    + mostrarFicheros()
    + generarCodigo()
    + anyadirUsuarios()
    + mostrarUsuarios()
    + compararPareja()
    + generarFicheroConcordancia()
}

Fichero --> Usuario : contiene
Pareja --> Usuario : se forma con 2

@enduml